# This is a basic workflow to help you get started with Actions

name: Windows build and test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  build:
    runs-on: windows-latest
    env:
      buildDir: '${{ github.workspace }}/build'
    steps:
      - uses: actions/checkout@v1
      
      - name: Run vcpkg
        run: |
          "vcpkg install gtest"
          "vcpkg install gtest:x64-windows"
      - name: build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" ..
          cmake --build . --target Test
      - name: Test
        run: |
          cd build/Debug
          Copy-Item ../TestMapv11.osu .
          Copy-Item ../TestMapv14.osu .
          ctest
